services:
  cymply-be:
    image: cymply/cymply-be:latest
    container_name: cymply-be
    restart: always
    ports:
      - 8080:8080
    env_file:
      - cymply.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.4.2-alpine
    container_name: cymply-redis
    ports:
      - 6379:6379
    # redis 작동 상태 확인
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 3