services:
  cymply-be:
    image: cymply/cymply-be:latest
    container_name: cymply-be
    restart: always
    ports:
      - 8080:8080
    env_file:
      - cymply.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.4.2-alpine
    container_name: cymply-redis
    restart: always              # ★ 추가
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]   # 쉘/grep 없이 단순화
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
