services:
  cymply-be:
    image: cymply/cymply-be:latest
    container_name: cymply-be
    restart: always
    ports:
      - 80:8080
    env_file:
      - cymply.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0.42
    container_name: cymply-mysql
    restart: always
    env_file:
      - cymply.env
    environment:
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    volumes:
      - 'cymply_mysql_data:/var/lib/mysql'
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--default-time-zone=Asia/Seoul"
    ]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 5


  redis:
    image: redis:7.4.2-alpine
    container_name: cymply-redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 3


volumes:
  cymply_mysql_data: