spring:
  application:
    name: cymply
  h2:
    console:
      enabled: true
      path: /h2-console

  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ymtUSixbVy7LnEt48m59RYfqXStWF0VFyea73USt/V65vFFh9gRjuyYi7qK8e5QtY1HFkiuKvrtWNBSKoGXpxA==
  security:
    oauth2:
      client:
        registration:
          google: # registration id
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${BASE_URL}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: email, profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${BASE_URL}/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

springdoc:
  swagger-ui:
    #    disable-swagger-default-url: true   #디폴트 페이지 안나오게
    #    display-request-duration: true
    #    operations-sorter: method
    #    tags-sorter: alpha
    path: /api-ui.html
    url: /api-docs    # 👈 반드시 이거!
  api-docs:
    path: /api-docs
  #  show-actuator: true
  #  default-consumes-media-type: application/json
  #  default-produces-media-type: application/json
  model-converters:
    generic-model-name-resolution-enabled: false