spring:
  config:
    activate:
      on-profile: prod

  app:
    host: http://54.180.35.200:8080
    client: http://www.cymply.kr

  datasource:
    url: jdbc:mysql://localhost:3306/cymply?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: cymply
    password: cymply
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    jwt:
      secret: ymtUSixbVy7LnEt48m59RYfqXStWF0VFyea73USt/V65vFFh9gRjuyYi7qK8e5QtY1HFkiuKvrtWNBSKoGXpxA==
      token-expire-policy:
        access: 360000 # 60 * 60 * 1000 => 1 hour
        refresh: 604800000 # 7 * 24 * 60 * 60 * 1000 => 7 days
        temporal: 6000000 # 100 * 60 * 1000 => 100 minutes

    oauth2:
      client:
        registration:
          google: # registration id
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${spring.app.host}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: email, profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${spring.app.host}/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

lastfm:
  api-key: ${LAST_FM_API_KEY}
  api:
    base-url: https://ws.audioscrobbler.com
    search-path: 2.0

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}
  auth:
    base-url: https://accounts.spotify.com
    token-path: /api/token
  api:
    base-url: https://api.spotify.com
    search-path: /v1/search

google:
  api-key: ${GOOGLE_API_KEY}